version: '3.3'

services:
    db:
      image: mysql:latest
      container_name: mysql-db  
      environment:
        - MYSQL_ROOT_PASSWORD=123
      ports:
        - "3306:3306"
    
  
    customerservice:                        
      image: timesheet-1-2.0            
      container_name: timesheet-1-2.0
      build:
        context: .                          
        dockerfile: Dockerfile             
      ports:
        - "8089:8089"                     


      depends_on:                           
        - db                              
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/timeSheetDevOps?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: 123